/**
 * indexer/src/mapping.ts — The Graph event handlers (Phase 6.2).
 *
 * AssemblyScript (compiled by graph-cli, NOT by our backend tsconfig). Types
 * (Batch, BatchVersion, Verification, event classes) are generated by
 * `graph codegen` from schema.graphql + the ABI. Deploy-time artifact.
 */
import {
  BatchRegistered,
  BatchSuperseded,
  ProductVerified
} from "../generated/ProductRegistry/ProductRegistry";
import { Batch, BatchVersion, Verification } from "../generated/schema";

export function handleBatchRegistered(event: BatchRegistered): void {
  const id = event.params.batchId;
  const batch = new Batch(id);
  batch.merkleRoot = event.params.merkleRoot;
  batch.totalProducts = event.params.totalProducts;
  batch.version = BigInt.fromI32(1);
  batch.createdAt = event.params.createdAt;
  batch.updatedAt = event.params.createdAt;
  batch.save();

  const v = new BatchVersion(id + "-1");
  v.batch = id;
  v.version = BigInt.fromI32(1);
  v.merkleRoot = event.params.merkleRoot;
  v.totalProducts = event.params.totalProducts;
  v.txHash = event.transaction.hash;
  v.timestamp = event.block.timestamp;
  v.save();
}

export function handleBatchSuperseded(event: BatchSuperseded): void {
  const id = event.params.batchId;
  const batch = Batch.load(id);
  if (batch == null) return;
  batch.merkleRoot = event.params.newRoot;
  batch.totalProducts = event.params.totalProducts;
  batch.version = event.params.version;
  batch.updatedAt = event.block.timestamp;
  batch.save();

  const v = new BatchVersion(id + "-" + event.params.version.toString());
  v.batch = id;
  v.version = event.params.version;
  v.merkleRoot = event.params.newRoot;
  v.totalProducts = event.params.totalProducts;
  v.txHash = event.transaction.hash;
  v.timestamp = event.block.timestamp;
  v.save();
}

export function handleProductVerified(event: ProductVerified): void {
  const id =
    event.transaction.hash.toHex() + "-" + event.logIndex.toString();
  const rec = new Verification(id);
  rec.batch = event.params.batchId;
  rec.leaf = event.params.leaf;
  rec.valid = event.params.valid;
  rec.txHash = event.transaction.hash;
  rec.timestamp = event.block.timestamp;
  rec.save();
}
