import type { SkfStore } from './types';

const dealers = [
  {
    id: 'dlr-nordic-01',
    did: 'did:voltus:dealer:dlr-nordic-01',
    display_name: 'Nordic Bearing Supply AB',
    region: 'Nordics',
    status: 'Authorized' as const,
    authorized_since: '2019-03-14',
  },
  {
    id: 'dlr-dach-07',
    did: 'did:voltus:dealer:dlr-dach-07',
    display_name: 'Autohaus Müller GmbH',
    region: 'DACH',
    status: 'Under review' as const,
    authorized_since: '2021-06-02',
  },
  {
    id: 'dlr-ce-12',
    did: 'did:voltus:dealer:dlr-ce-12',
    display_name: 'Eastern Motors Parts',
    region: 'Central Europe',
    status: 'Warned' as const,
    authorized_since: '2018-11-20',
  },
  {
    id: 'dlr-uk-03',
    did: 'did:voltus:dealer:dlr-uk-03',
    display_name: 'Midlands Industrial Supply',
    region: 'UK & Ireland',
    status: 'Suspended' as const,
    authorized_since: '2017-01-09',
  },
  {
    id: 'dlr-emea-99',
    did: 'did:voltus:dealer:dlr-emea-99',
    display_name: 'Grey Channel Trading Ltd',
    region: 'EMEA',
    status: 'Blacklisted' as const,
    authorized_since: '2015-04-22',
  },
];

const products: SkfStore['products'] = {
  'SN-88421-A': { serial: 'SN-88421-A', sku: '6205-2RS/VT378', batch_id: 'B-2025-0412', manufactured_at: '2025-04-18' },
  'SN-77210-C': { serial: 'SN-77210-C', sku: '6308-2Z/C3', batch_id: 'B-2025-0388', manufactured_at: '2025-03-22' },
  'SN-66105-B': { serial: 'SN-66105-B', sku: '22212 EK/C3', batch_id: 'B-2024-1201', manufactured_at: '2024-12-08' },
  'SN-55098-D': { serial: 'SN-55098-D', sku: 'NU 206 ECML', batch_id: 'B-2025-0205', manufactured_at: '2025-02-14' },
  'SN-44901-E': { serial: 'SN-44901-E', sku: '6205-2RS/VT378', batch_id: 'B-2025-0099', manufactured_at: '2025-01-30' },
};

function custody(serial: string, dealerDid: string, dealerName: string, anomaly?: string | null): SkfStore['custodyChains'][string] {
  return [
    { actor_did: 'did:voltus:plant:gothenburg-01', actor_role: 'PLANT', actor_display_name: 'SKF Gothenburg Plant', occurred_at: '2025-04-20T08:00:00Z', vc_id: 'vc:plant:001', on_chain_ref: '0x8a3f…c21d', anomaly_flag: null },
    { actor_did: 'did:voltus:dist:emea-hub', actor_role: 'DISTRIBUTOR', actor_display_name: 'SKF EMEA Distribution Hub', occurred_at: '2025-04-25T14:30:00Z', vc_id: 'vc:dist:044', on_chain_ref: '0x2b91…f8ae', anomaly_flag: null },
    { actor_did: dealerDid, actor_role: 'DEALER', actor_display_name: dealerName, occurred_at: '2025-05-02T09:15:00Z', vc_id: 'vc:dealer:112', on_chain_ref: '0x4c72…a901', anomaly_flag: anomaly ?? null },
    { actor_did: 'did:voltus:sc:rotterdam-02', actor_role: 'SERVICE_CENTRE', actor_display_name: 'Rotterdam Service Centre', occurred_at: '2026-05-28T11:00:00Z', vc_id: 'vc:sc:089', on_chain_ref: null, anomaly_flag: null },
    { actor_did: 'did:voltus:customer:cust-4421', actor_role: 'CUSTOMER', actor_display_name: 'Fleet Operator BV', occurred_at: '2026-05-28T11:45:00Z', vc_id: 'vc:cust:221', on_chain_ref: null, anomaly_flag: null },
  ];
}

export const skfSeed: SkfStore = {
  dealers,
  products,
  custodyChains: {
    'SN-88421-A': custody('SN-88421-A', dealers[2].did, dealers[2].display_name, 'dealer_not_authorized'),
    'SN-77210-C': custody('SN-77210-C', dealers[1].did, dealers[1].display_name),
    'SN-66105-B': custody('SN-66105-B', dealers[3].did, dealers[3].display_name, 'qr_replay_suspected'),
    'SN-55098-D': custody('SN-55098-D', dealers[0].did, dealers[0].display_name),
    'SN-44901-E': custody('SN-44901-E', dealers[3].did, dealers[3].display_name),
  },
  serviceRequests: [
    {
      sr_id: 'SR-2026-1042',
      customer_display_name: 'Fleet Operator BV',
      service_centre: { id: 'sc-rotterdam-02', display_name: 'Rotterdam Service Centre' },
      technician: { did: 'did:voltus:tech:jan-van-berg', display_name: 'Jan van Berg' },
      product_serial: 'SN-88421-A',
      opened_at: '2026-05-28T10:30:00Z',
      status: 'In Progress',
      verification: {
        result: 'COUNTERFEIT',
        confidence: 0.94,
        timestamp: '2026-05-28T11:52:00Z',
        merkle_root: '0x7f3a…b912',
        chain_anchor_ref: '0x1d4e…88af',
        attribution: [
          { check: 'merkle_proof_valid', passed: true, weight: 0.2, label: 'Merkle proof valid' },
          { check: 'root_anchored_on_chain', passed: true, weight: 0.15, label: 'Root anchored on chain' },
          { check: 'batch_active', passed: true, weight: 0.1, label: 'Batch active' },
          { check: 'dealer_authorized', passed: false, weight: 0.2, label: 'Dealer authorized' },
          { check: 'custody_continuous', passed: false, weight: 0.15, label: 'Custody continuous' },
          { check: 'qr_not_replayed', passed: true, weight: 0.1, label: 'QR not replayed' },
          { check: 'region_consistent', passed: false, weight: 0.1, label: 'Region consistent' },
        ],
      },
    },
    {
      sr_id: 'SR-2026-1038',
      customer_display_name: 'Bavaria Motors AG',
      service_centre: { id: 'sc-munich-01', display_name: 'Munich Service Centre' },
      technician: { did: 'did:voltus:tech:lena-fischer', display_name: 'Lena Fischer' },
      product_serial: 'SN-77210-C',
      opened_at: '2026-05-27T08:00:00Z',
      status: 'Open',
      verification: {
        result: 'NOT_YET_SCANNED',
        confidence: null,
        timestamp: null,
        merkle_root: null,
        chain_anchor_ref: null,
        attribution: [],
      },
    },
    {
      sr_id: 'SR-2026-1031',
      customer_display_name: 'North Sea Wind Services',
      service_centre: { id: 'sc-hamburg-03', display_name: 'Hamburg Service Centre' },
      technician: { did: 'did:voltus:tech:thomas-weber', display_name: 'Thomas Weber' },
      product_serial: 'SN-55098-D',
      opened_at: '2026-05-26T14:00:00Z',
      status: 'Closed',
      verification: {
        result: 'AUTHENTIC',
        confidence: 0.99,
        timestamp: '2026-05-26T14:22:00Z',
        merkle_root: '0x9c21…4f7a',
        chain_anchor_ref: '0x3a8b…12cd',
        attribution: [
          { check: 'merkle_proof_valid', passed: true, weight: 0.2, label: 'Merkle proof valid' },
          { check: 'root_anchored_on_chain', passed: true, weight: 0.15, label: 'Root anchored on chain' },
          { check: 'batch_active', passed: true, weight: 0.1, label: 'Batch active' },
          { check: 'dealer_authorized', passed: true, weight: 0.2, label: 'Dealer authorized' },
          { check: 'custody_continuous', passed: true, weight: 0.15, label: 'Custody continuous' },
          { check: 'qr_not_replayed', passed: true, weight: 0.1, label: 'QR not replayed' },
          { check: 'region_consistent', passed: true, weight: 0.1, label: 'Region consistent' },
        ],
      },
    },
    {
      sr_id: 'SR-2026-1025',
      customer_display_name: 'Midlands Fleet Ltd',
      service_centre: { id: 'sc-birmingham-01', display_name: 'Birmingham Service Centre' },
      technician: { did: 'did:voltus:tech:sarah-clarke', display_name: 'Sarah Clarke' },
      product_serial: 'SN-66105-B',
      opened_at: '2026-05-25T09:30:00Z',
      status: 'In Progress',
      verification: {
        result: 'CANNOT_VERIFY',
        confidence: 0.41,
        timestamp: '2026-05-25T10:05:00Z',
        merkle_root: '0x5e88…c301',
        chain_anchor_ref: '0x7b22…9efa',
        attribution: [
          { check: 'merkle_proof_valid', passed: false, weight: 0.2, label: 'Merkle proof valid' },
          { check: 'root_anchored_on_chain', passed: true, weight: 0.15, label: 'Root anchored on chain' },
          { check: 'batch_active', passed: true, weight: 0.1, label: 'Batch active' },
          { check: 'dealer_authorized', passed: false, weight: 0.2, label: 'Dealer authorized' },
          { check: 'custody_continuous', passed: false, weight: 0.15, label: 'Custody continuous' },
          { check: 'qr_not_replayed', passed: false, weight: 0.1, label: 'QR not replayed' },
          { check: 'region_consistent', passed: true, weight: 0.1, label: 'Region consistent' },
        ],
      },
    },
    ...Array.from({ length: 8 }, (_, i) => ({
      sr_id: `SR-2026-10${String(20 - i).padStart(2, '0')}`,
      customer_display_name: `Customer ${i + 1} GmbH`,
      service_centre: { id: `sc-${i}`, display_name: `Service Centre ${i + 1}` },
      technician: { did: `did:voltus:tech:tech-${i}`, display_name: `Technician ${i + 1}` },
      product_serial: i % 2 === 0 ? 'SN-55098-D' : 'SN-44901-E',
      opened_at: `2026-05-${String(24 - i).padStart(2, '0')}T08:00:00Z`,
      status: (i % 3 === 0 ? 'Closed' : 'Open') as const,
      verification: null,
    })),
  ],
  counterfeitReports: [
    { report_id: 'CR-2026-0088', sr_id: 'SR-2026-1042', dealer_did: dealers[2].did, product_serial: 'SN-88421-A', sku: '6205-2RS/VT378', severity: 'CONFIRMED_VISUAL', failure_modes: ['marking_anomaly', 'packaging_anomaly'], photos: [], lab_report_url: null, technician_did: 'did:voltus:tech:jan-van-berg', reporter_service_centre: 'Rotterdam Service Centre', reported_at: '2026-05-20T15:00:00Z', status: 'Confirmed', customer_consent_to_share: true },
    { report_id: 'CR-2026-0081', sr_id: 'SR-2026-1020', dealer_did: dealers[2].did, product_serial: 'SN-44901-E', sku: '6205-2RS/VT378', severity: 'CONFIRMED_VISUAL', failure_modes: ['dimensional_mismatch'], photos: [], lab_report_url: null, technician_did: 'did:voltus:tech:tech-2', reporter_service_centre: 'Service Centre 3', reported_at: '2026-04-12T10:00:00Z', status: 'Confirmed', customer_consent_to_share: false },
    { report_id: 'CR-2026-0075', sr_id: 'SR-2026-1018', dealer_did: dealers[2].did, product_serial: 'SN-66105-B', sku: '22212 EK/C3', severity: 'SUSPECTED', failure_modes: ['qr_invalid'], photos: [], lab_report_url: null, technician_did: 'did:voltus:tech:tech-4', reporter_service_centre: 'Service Centre 5', reported_at: '2026-03-28T09:00:00Z', status: 'Under review', customer_consent_to_share: false },
    { report_id: 'CR-2026-0070', sr_id: 'SR-2026-1015', dealer_did: dealers[2].did, product_serial: 'SN-77210-C', sku: '6308-2Z/C3', severity: 'CONFIRMED_VISUAL', failure_modes: ['material_mismatch', 'premature_failure'], photos: [], lab_report_url: null, technician_did: 'did:voltus:tech:lena-fischer', reporter_service_centre: 'Munich Service Centre', reported_at: '2026-02-14T11:00:00Z', status: 'Confirmed', customer_consent_to_share: true },
    { report_id: 'CR-2026-0062', sr_id: 'SR-2026-1010', dealer_did: dealers[1].did, product_serial: 'SN-77210-C', sku: '6308-2Z/C3', severity: 'SUSPECTED', failure_modes: ['marking_anomaly'], photos: [], lab_report_url: null, technician_did: 'did:voltus:tech:tech-1', reporter_service_centre: 'Service Centre 2', reported_at: '2026-05-10T14:00:00Z', status: 'Submitted', customer_consent_to_share: false },
    { report_id: 'CR-2026-0055', sr_id: 'SR-2026-1008', dealer_did: dealers[1].did, product_serial: 'SN-55098-D', sku: 'NU 206 ECML', severity: 'SUSPECTED', failure_modes: ['packaging_anomaly'], photos: [], lab_report_url: null, technician_did: 'did:voltus:tech:tech-0', reporter_service_centre: 'Service Centre 1', reported_at: '2026-04-22T08:00:00Z', status: 'Under review', customer_consent_to_share: false },
    { report_id: 'CR-2026-0048', sr_id: 'SR-2026-1005', dealer_did: dealers[3].did, product_serial: 'SN-66105-B', sku: '22212 EK/C3', severity: 'CONFIRMED_LAB', failure_modes: ['material_mismatch', 'dimensional_mismatch'], photos: [], lab_report_url: '/docs/lab-report-0048.pdf', technician_did: 'did:voltus:tech:sarah-clarke', reporter_service_centre: 'Birmingham Service Centre', reported_at: '2026-01-18T16:00:00Z', status: 'Confirmed', customer_consent_to_share: true },
    { report_id: 'CR-2026-0041', sr_id: 'SR-2026-1003', dealer_did: dealers[3].did, product_serial: 'SN-44901-E', sku: '6205-2RS/VT378', severity: 'CONFIRMED_LAB', failure_modes: ['premature_failure'], photos: [], lab_report_url: '/docs/lab-report-0041.pdf', technician_did: 'did:voltus:tech:tech-3', reporter_service_centre: 'Service Centre 4', reported_at: '2025-12-05T10:00:00Z', status: 'Confirmed', customer_consent_to_share: true },
    { report_id: 'CR-2025-0399', sr_id: 'SR-2025-0881', dealer_did: dealers[3].did, product_serial: 'SN-44901-E', sku: '6205-2RS/VT378', severity: 'CONFIRMED_VISUAL', failure_modes: ['qr_missing'], photos: [], lab_report_url: null, technician_did: 'did:voltus:tech:tech-5', reporter_service_centre: 'Service Centre 6', reported_at: '2025-11-20T09:00:00Z', status: 'Confirmed', customer_consent_to_share: false },
    { report_id: 'CR-2025-0388', sr_id: 'SR-2025-0870', dealer_did: dealers[3].did, product_serial: 'SN-66105-B', sku: '22212 EK/C3', severity: 'CONFIRMED_VISUAL', failure_modes: ['marking_anomaly'], photos: [], lab_report_url: null, technician_did: 'did:voltus:tech:tech-6', reporter_service_centre: 'Service Centre 7', reported_at: '2025-10-08T11:00:00Z', status: 'Confirmed', customer_consent_to_share: true },
    { report_id: 'CR-2025-0370', sr_id: 'SR-2025-0850', dealer_did: dealers[3].did, product_serial: 'SN-77210-C', sku: '6308-2Z/C3', severity: 'SUSPECTED', failure_modes: ['packaging_anomaly'], photos: [], lab_report_url: null, technician_did: 'did:voltus:tech:tech-7', reporter_service_centre: 'Service Centre 8', reported_at: '2025-09-15T08:00:00Z', status: 'Dismissed', customer_consent_to_share: false },
    { report_id: 'CR-2024-1201', sr_id: 'SR-2024-0440', dealer_did: dealers[4].did, product_serial: 'SN-44901-E', sku: '6205-2RS/VT378', severity: 'CONFIRMED_LAB', failure_modes: ['material_mismatch'], photos: [], lab_report_url: '/docs/lab-report-1201.pdf', technician_did: 'did:voltus:tech:legacy-01', reporter_service_centre: 'London Service Centre', reported_at: '2024-08-30T12:00:00Z', status: 'Confirmed', customer_consent_to_share: true },
  ],
  dealerEnforcementLog: [
    { event_id: 'ENF-001', dealer_did: dealers[2].did, type: 'WARN', occurred_at: '2026-02-01T10:00:00Z', actor: 'did:voltus:oem:brand-protection', dao_proposal_ref: 'DAO-2026-0042', on_chain_tx: '0xwarn…01', rationale_short: 'Elevated counterfeit signal — 3 confirmed visual reports in 90d' },
    { event_id: 'ENF-002', dealer_did: dealers[3].did, type: 'SUSPEND', occurred_at: '2026-01-15T14:00:00Z', actor: 'DAO', dao_proposal_ref: 'DAO-2026-0038', on_chain_tx: '0xsusp…02', rationale_short: 'DAO simple majority — 90-day suspension for lab-confirmed counterfeits' },
    { event_id: 'ENF-003', dealer_did: dealers[4].did, type: 'BLACKLIST', occurred_at: '2024-09-10T09:00:00Z', actor: 'DAO', dao_proposal_ref: 'DAO-2024-0112', on_chain_tx: '0xblk…03', rationale_short: 'Super-majority blacklist — repeated lab-confirmed counterfeits' },
    { event_id: 'ENF-004', dealer_did: dealers[0].did, type: 'APPEAL', occurred_at: '2025-06-01T11:00:00Z', actor: 'did:voltus:dealer:dlr-nordic-01', dao_proposal_ref: null, on_chain_tx: null, rationale_short: 'Annual authorization review — no action required' },
  ],
  daoProposals: [
    {
      proposal_id: 'DAO-2026-0045',
      dealer_did: dealers[2].did,
      action_type: 'SUSPEND',
      governance: 'dao_simple_majority',
      opened_at: '2026-05-22T08:00:00Z',
      closes_at: '2026-06-05T08:00:00Z',
      rationale: 'Eastern Motors Parts has accumulated 4 CONFIRMED_VISUAL counterfeit reports in 90 days with distinct service centre reporters. Signal score 78/100. Recommend 90-day suspension pending remediation.',
      evidence_hash: '0xevid…445',
      votes: { for: 12, against: 4, abstain: 2, quorum_required: 15 },
      status: 'Open',
      on_chain_tx: null,
    },
    {
      proposal_id: 'DAO-2026-0042',
      dealer_did: dealers[2].did,
      action_type: 'WARN',
      governance: 'single_signer',
      opened_at: '2026-02-01T09:00:00Z',
      closes_at: '2026-02-01T09:05:00Z',
      rationale: 'Formal warning issued by OEM Brand Protection Lead following threshold breach on counterfeit rate.',
      evidence_hash: '0xevid…442',
      votes: { for: 1, against: 0, abstain: 0, quorum_required: 1 },
      status: 'Executed',
      on_chain_tx: '0xwarn…01',
    },
    {
      proposal_id: 'DAO-2026-0038',
      dealer_did: dealers[3].did,
      action_type: 'SUSPEND',
      governance: 'dao_simple_majority',
      opened_at: '2026-01-10T10:00:00Z',
      closes_at: '2026-01-24T10:00:00Z',
      rationale: 'Midlands Industrial Supply — 2 lab-confirmed reports, 7 total reports in window. Simple majority suspension for 90 days.',
      evidence_hash: '0xevid…338',
      votes: { for: 18, against: 3, abstain: 1, quorum_required: 15 },
      status: 'Executed',
      on_chain_tx: '0xsusp…02',
    },
    {
      proposal_id: 'DAO-2024-0112',
      dealer_did: dealers[4].did,
      action_type: 'BLACKLIST',
      governance: 'dao_super_majority',
      opened_at: '2024-08-20T08:00:00Z',
      closes_at: '2024-09-03T08:00:00Z',
      rationale: 'Grey Channel Trading Ltd — permanent blacklist. Lab-confirmed counterfeits, repeat offender pattern, regulator notification required.',
      evidence_hash: '0xevid…112',
      votes: { for: 42, against: 5, abstain: 2, quorum_required: 40 },
      status: 'Executed',
      on_chain_tx: '0xblk…03',
    },
  ],
  dealerSignalScores: {
    [dealers[0].did]: { score: 8, attributions: [{ factor: 'confirmed_lab_reports', contribution: 0, label: 'No lab reports' }, { factor: 'distinct_service_centres', contribution: 0, label: 'Single reporter' }] },
    [dealers[1].did]: { score: 34, attributions: [{ factor: 'confirmed_lab_reports', contribution: 10, label: '0 lab reports' }, { factor: 'distinct_service_centres', contribution: 12, label: '2 distinct reporters' }, { factor: 'failure_mode_concentration', contribution: 8, label: 'Marking anomalies' }, { factor: 'repeat_offender_window', contribution: 4, label: '2 reports in 90d' }] },
    [dealers[2].did]: { score: 78, attributions: [{ factor: 'confirmed_lab_reports', contribution: 15, label: '0 lab, 3 visual confirmed' }, { factor: 'distinct_service_centres', contribution: 20, label: '4 distinct reporters' }, { factor: 'failure_mode_concentration', contribution: 15, label: 'Multiple failure modes' }, { factor: 'repeat_offender_window', contribution: 15, label: '4 reports in 90d' }, { factor: 'customer_complaint_volume', contribution: 13, label: 'Elevated complaints' }] },
    [dealers[3].did]: { score: 91, attributions: [{ factor: 'confirmed_lab_reports', contribution: 35, label: '2 lab-confirmed reports' }, { factor: 'distinct_service_centres', contribution: 20, label: '5 distinct reporters' }, { factor: 'failure_mode_concentration', contribution: 15, label: 'Material mismatch cluster' }, { factor: 'repeat_offender_window', contribution: 15, label: '7 reports in window' }, { factor: 'customer_complaint_volume', contribution: 6, label: 'Warranty claims linked' }] },
    [dealers[4].did]: { score: 100, attributions: [{ factor: 'confirmed_lab_reports', contribution: 35, label: 'Lab confirmed' }, { factor: 'distinct_service_centres', contribution: 20, label: 'Multiple reporters' }, { factor: 'repeat_offender_window', contribution: 25, label: 'Lifetime repeat offender' }, { factor: 'failure_mode_concentration', contribution: 20, label: 'Severe concentration' }] },
  },
};
